/**
 * Canonical constant billboard catalog.
 * Defines the 10 fixed billboard slots, their constant billboard numbers (1-10),
 * physical 3D dimensions, and monthly USD advertising rates ($5 - $30).
 */
const BILLBOARD_CATALOG = [
  {
    billboardNumber: 1,
    code: "bb_commerce_ave",
    name: "Downtown Financial Avenue Mega-Screen",
    type: "Financial Hub Rooftop Billboard",
    rateUSD: 30,
    rateINR: 2490,
    billingCycle: "MONTHLY",
    plotDistrict: "Financial District",
    width: 15.0,
    height: 8.2,
    elevation: 12.0,
    isGantry: false,
    offsetX: 92,
    offsetZ: 32,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 2,
    code: "bb_cp_south",
    name: "Central Park South Mega-Gantry",
    type: "Overhead Highway Mega-Screen",
    rateUSD: 30,
    rateINR: 2490,
    billingCycle: "MONTHLY",
    plotDistrict: "Central Plaza",
    width: 14.0,
    height: 7.5,
    elevation: 8.0,
    isGantry: true,
    offsetX: 0,
    offsetZ: 8,
    isPlazaZ1: true,
    yaw: 0,
  },
  {
    billboardNumber: 3,
    code: "bb_cp_north",
    name: "Central Park North Digital Plaza Screen",
    type: "Grand Plaza LED Billboard",
    rateUSD: 25,
    rateINR: 2075,
    billingCycle: "MONTHLY",
    plotDistrict: "Central Plaza",
    width: 12.0,
    height: 6.8,
    elevation: 7.0,
    isGantry: false,
    offsetX: 0,
    offsetZ: -8,
    isPlazaZ0: true,
    yaw: Math.PI,
  },
  {
    billboardNumber: 4,
    code: "bb_highway_east",
    name: "Commerce Highway Dual-Sided Gantry",
    type: "Highway Overhead LED Billboard",
    rateUSD: 20,
    rateINR: 1660,
    billingCycle: "MONTHLY",
    plotDistrict: "Commerce Way",
    width: 14.0,
    height: 7.2,
    elevation: 8.5,
    isGantry: true,
    offsetX: 120,
    offsetZ: -45,
    yaw: 0,
  },
  {
    billboardNumber: 5,
    code: "bb_waterfront",
    name: "Waterfront Marina Scenic Billboard",
    type: "Coastal Marina Mega-Billboard",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Velora Harbor",
    width: 11.0,
    height: 6.2,
    elevation: 6.5,
    isGantry: false,
    offsetX: -120,
    offsetZ: 45,
    yaw: Math.PI,
  },
  {
    billboardNumber: 6,
    code: "bb_fountain_east",
    name: "Botanical Promenade East Video Totem",
    type: "Promenade Digital Pillar",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Botanical Gardens",
    width: 7.5,
    height: 9.5,
    elevation: 2.2,
    isGantry: false,
    offsetX: 28,
    offsetZ: 14,
    yaw: -Math.PI / 4,
  },
  {
    billboardNumber: 7,
    code: "bb_fountain_west",
    name: "Botanical Promenade West Video Totem",
    type: "Promenade Digital Pillar",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Botanical Gardens",
    width: 7.5,
    height: 9.5,
    elevation: 2.2,
    isGantry: false,
    offsetX: -28,
    offsetZ: -14,
    yaw: Math.PI * 0.75,
  },
  {
    billboardNumber: 8,
    code: "bb_tech_hub",
    name: "Westside Tech District Video Totem",
    type: "Tech Hub Interactive Display",
    rateUSD: 10,
    rateINR: 830,
    billingCycle: "MONTHLY",
    plotDistrict: "Cyber District",
    width: 8.0,
    height: 8.5,
    elevation: 3.0,
    isGantry: false,
    offsetX: -88,
    offsetZ: -32,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 9,
    code: "bb_north_blvd",
    name: "North Coastal Boulevard LED Screen",
    type: "Boulevard Roadside Display",
    rateUSD: 10,
    rateINR: 830,
    billingCycle: "MONTHLY",
    plotDistrict: "Velora Harbor",
    width: 10.0,
    height: 6.0,
    elevation: 5.5,
    isGantry: false,
    offsetX: 42,
    offsetZ: -110,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 10,
    code: "bb_south_blvd",
    name: "South Parkview Boulevard Billboard",
    type: "Parkview Roadside Display",
    rateUSD: 5,
    rateINR: 415,
    billingCycle: "MONTHLY",
    plotDistrict: "Velora Outskirts",
    width: 10.0,
    height: 6.0,
    elevation: 5.5,
    isGantry: false,
    offsetX: -42,
    offsetZ: 110,
    yaw: -Math.PI / 2,
  },
];

module.exports = { BILLBOARD_CATALOG };

