/**
 * Canonical constant billboard catalog - the single source of truth for what
 * the city has for sale.
 *
 *   #1 – #10   City-wide landmark billboard slots ($5 – $30 / month)
 *   #11 – #56  TIMES SQUARE Commercialized Facade Screens, Marquees,
 *              Vertical Banners, Wedge Tower Screens & Plaza Totems ($15 – $90 / month)
 *
 * Times Square sells commercial advertising signage across its building facades.
 * Every mounted screen is an interactive, buyable slot connected to backend payments.
 */
const BILLBOARD_CATALOG = [
  // ── CITY-WIDE BILLBOARDS (#1 – #10) ──────────────────────────────────
  {
    billboardNumber: 1,
    code: "bb_commerce_ave",
    name: "Downtown Financial Avenue Mega-Screen",
    type: "Financial Hub Rooftop Billboard",
    rateUSD: 30,
    rateINR: 2490,
    billingCycle: "MONTHLY",
    plotDistrict: "Financial District",
    width: 15.0,
    height: 8.2,
    elevation: 12.0,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: 92,
    offsetZ: 32,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 2,
    code: "bb_cp_south",
    name: "Central Park South Mega-Gantry",
    type: "Overhead Highway Mega-Screen",
    rateUSD: 30,
    rateINR: 2490,
    billingCycle: "MONTHLY",
    plotDistrict: "Central Plaza",
    width: 14.0,
    height: 7.5,
    elevation: 8.0,
    mount: "gantry",
    orientation: "landscape",
    isGantry: true,
    offsetX: 0,
    offsetZ: 8,
    isPlazaZ1: true,
    yaw: 0,
  },
  {
    billboardNumber: 3,
    code: "bb_cp_north",
    name: "Central Park North Digital Plaza Screen",
    type: "Grand Plaza LED Billboard",
    rateUSD: 25,
    rateINR: 2075,
    billingCycle: "MONTHLY",
    plotDistrict: "Central Plaza",
    width: 12.0,
    height: 6.8,
    elevation: 7.0,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: 0,
    offsetZ: -8,
    isPlazaZ0: true,
    yaw: Math.PI,
  },
  {
    billboardNumber: 4,
    code: "bb_highway_east",
    name: "Commerce Highway Dual-Sided Gantry",
    type: "Highway Overhead LED Billboard",
    rateUSD: 20,
    rateINR: 1660,
    billingCycle: "MONTHLY",
    plotDistrict: "Commerce Way",
    width: 14.0,
    height: 7.2,
    elevation: 8.5,
    mount: "gantry",
    orientation: "landscape",
    isGantry: true,
    offsetX: 120,
    offsetZ: -45,
    yaw: 0,
  },
  {
    billboardNumber: 5,
    code: "bb_waterfront",
    name: "Waterfront Marina Scenic Billboard",
    type: "Coastal Marina Mega-Billboard",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Velora Harbor",
    width: 11.0,
    height: 6.2,
    elevation: 6.5,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: -120,
    offsetZ: 45,
    yaw: Math.PI,
  },
  {
    billboardNumber: 6,
    code: "bb_fountain_east",
    name: "Botanical Promenade East Video Totem",
    type: "Promenade Digital Pillar",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Botanical Gardens",
    width: 7.5,
    height: 9.5,
    elevation: 2.2,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: 28,
    offsetZ: 14,
    yaw: -Math.PI / 4,
  },
  {
    billboardNumber: 7,
    code: "bb_fountain_west",
    name: "Botanical Promenade West Video Totem",
    type: "Promenade Digital Pillar",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Botanical Gardens",
    width: 7.5,
    height: 9.5,
    elevation: 2.2,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: -28,
    offsetZ: -14,
    yaw: Math.PI * 0.75,
  },
  {
    billboardNumber: 8,
    code: "bb_tech_hub",
    name: "Westside Tech District Video Totem",
    type: "Tech Hub Interactive Display",
    rateUSD: 10,
    rateINR: 830,
    billingCycle: "MONTHLY",
    plotDistrict: "Cyber District",
    width: 8.0,
    height: 8.5,
    elevation: 3.0,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: -88,
    offsetZ: -32,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 9,
    code: "bb_north_blvd",
    name: "North Coastal Boulevard LED Screen",
    type: "Boulevard Roadside Display",
    rateUSD: 10,
    rateINR: 830,
    billingCycle: "MONTHLY",
    plotDistrict: "Velora Harbor",
    width: 10.0,
    height: 6.0,
    elevation: 5.5,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: 42,
    offsetZ: -110,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 10,
    code: "bb_south_blvd",
    name: "South Parkview Boulevard Billboard",
    type: "Parkview Roadside Display",
    rateUSD: 5,
    rateINR: 415,
    billingCycle: "MONTHLY",
    plotDistrict: "Velora Outskirts",
    width: 10.0,
    height: 6.0,
    elevation: 5.5,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: -42,
    offsetZ: 110,
    yaw: -Math.PI / 2,
  },

  // ── TIMES SQUARE NORTH FRONTAGE (#11 – #19) ──────────────────────────
  {
    billboardNumber: 11,
    code: "bb_ts_north_marquee",
    name: "Times Square North Grand Marquee",
    type: "Building-Mounted Mega-Screen",
    rateUSD: 90,
    rateINR: 7470,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 26.0,
    height: 13.0,
    elevation: 15.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -30,
    offsetZ: -15,
    yaw: 0,
  },
  {
    billboardNumber: 12,
    code: "bb_ts_north_tower",
    name: "Times Square North Tower Screen",
    type: "Building-Mounted Mega-Screen",
    rateUSD: 80,
    rateINR: 6640,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 22.0,
    height: 11.0,
    elevation: 31.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 34,
    offsetZ: -15,
    yaw: 0,
  },
  {
    billboardNumber: 13,
    code: "bb_ts_north_portrait",
    name: "Times Square North Broadway Vertical Banner",
    type: "Vertical Building Banner",
    rateUSD: 65,
    rateINR: 5395,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 9.0,
    height: 20.0,
    elevation: 10.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: 2,
    offsetZ: -15,
    yaw: 0,
  },
  {
    billboardNumber: 14,
    code: "bb_ts_north_facade_w",
    name: "Times Square North Facade Display (West)",
    type: "Building-Mounted Display",
    rateUSD: 50,
    rateINR: 4150,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 18.0,
    height: 10.0,
    elevation: 24.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -54,
    offsetZ: -15,
    yaw: 0,
  },
  {
    billboardNumber: 15,
    code: "bb_ts_north_facade_e",
    name: "Times Square North Facade Display (East)",
    type: "Building-Mounted Display",
    rateUSD: 50,
    rateINR: 4150,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 18.0,
    height: 10.0,
    elevation: 24.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 56,
    offsetZ: -15,
    yaw: 0,
  },
  {
    billboardNumber: 16,
    code: "bb_ts_north_upper",
    name: "Times Square North Crown Screen",
    type: "Skyline High-Rise Screen",
    rateUSD: 50,
    rateINR: 4150,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 24.0,
    height: 8.0,
    elevation: 46.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -12,
    offsetZ: -15,
    yaw: 0,
  },
  {
    billboardNumber: 17,
    code: "bb_ts_north_ribbon_1",
    name: "Times Square North Broadway Ribbon",
    type: "Ribbon LED Screen",
    rateUSD: 20,
    rateINR: 1660,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 28.0,
    height: 4.2,
    elevation: 10.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -54,
    offsetZ: -15,
    yaw: 0,
  },
  {
    billboardNumber: 18,
    code: "bb_ts_north_ribbon_2",
    name: "Times Square North 7th Ave Ribbon",
    type: "Ribbon LED Screen",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 28.0,
    height: 4.2,
    elevation: 18.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 56,
    offsetZ: -15,
    yaw: 0,
  },
  {
    billboardNumber: 19,
    code: "bb_ts_north_mid",
    name: "Times Square North Mid-Tier Display",
    type: "Building Facade Display",
    rateUSD: 35,
    rateINR: 2905,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 14.0,
    height: 8.0,
    elevation: 12.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 20,
    offsetZ: -15,
    yaw: 0,
  },

  // ── TIMES SQUARE SOUTH FRONTAGE & LANDMARK TOWER (#20 – #30) ─────────
  {
    billboardNumber: 20,
    code: "bb_ts_south_marquee",
    name: "Times Square South Grand Marquee",
    type: "Building-Mounted Mega-Screen",
    rateUSD: 90,
    rateINR: 7470,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 26.0,
    height: 13.0,
    elevation: 14.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 30,
    offsetZ: 15,
    yaw: Math.PI,
  },
  {
    billboardNumber: 21,
    code: "bb_ts_south_portrait",
    name: "Times Square South 7th Ave Vertical Banner",
    type: "Vertical Building Banner",
    rateUSD: 70,
    rateINR: 5810,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 9.0,
    height: 20.0,
    elevation: 10.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: -24,
    offsetZ: 15,
    yaw: Math.PI,
  },
  {
    billboardNumber: 22,
    code: "bb_ts_south_ribbon",
    name: "Times Square South Wrap Ribbon",
    type: "Wrap-Around Ribbon LED",
    rateUSD: 25,
    rateINR: 2075,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 24.0,
    height: 5.5,
    elevation: 26.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -46,
    offsetZ: 15,
    yaw: Math.PI,
  },
  {
    billboardNumber: 23,
    code: "bb_ts_south_facade_w",
    name: "Times Square South Facade Display (West)",
    type: "Building-Mounted Display",
    rateUSD: 50,
    rateINR: 4150,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 18.0,
    height: 10.0,
    elevation: 24.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -54,
    offsetZ: 15,
    yaw: Math.PI,
  },
  {
    billboardNumber: 24,
    code: "bb_ts_south_facade_e",
    name: "Times Square South Facade Display (East)",
    type: "Building-Mounted Display",
    rateUSD: 50,
    rateINR: 4150,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 18.0,
    height: 10.0,
    elevation: 24.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 56,
    offsetZ: 15,
    yaw: Math.PI,
  },
  {
    billboardNumber: 25,
    code: "bb_ts_south_upper",
    name: "Times Square South High Screen",
    type: "Skyline High-Rise Screen",
    rateUSD: 45,
    rateINR: 3735,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 20.0,
    height: 9.0,
    elevation: 44.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 12,
    offsetZ: 15,
    yaw: Math.PI,
  },
  {
    billboardNumber: 26,
    code: "bb_ts_landmark_lower",
    name: "Times Square Wedge Tower Mega-Screen",
    type: "Landmark Tower Mega-Screen",
    rateUSD: 60,
    rateINR: 4980,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 17.0,
    height: 18.0,
    elevation: 14.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: 62,
    offsetZ: 15,
    yaw: Math.PI,
  },
  {
    billboardNumber: 27,
    code: "bb_ts_landmark_mid_1",
    name: "Times Square Wedge Tower Mid-Screen 1",
    type: "Landmark Tower Display",
    rateUSD: 50,
    rateINR: 4150,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 17.0,
    height: 16.0,
    elevation: 34.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: 62,
    offsetZ: 15,
    yaw: Math.PI,
  },
  {
    billboardNumber: 28,
    code: "bb_ts_landmark_mid_2",
    name: "Times Square Wedge Tower Mid-Screen 2",
    type: "Landmark Tower Display",
    rateUSD: 40,
    rateINR: 3320,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 17.0,
    height: 14.0,
    elevation: 52.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: 62,
    offsetZ: 15,
    yaw: Math.PI,
  },
  {
    billboardNumber: 29,
    code: "bb_ts_landmark_upper_1",
    name: "Times Square Wedge Tower High-Screen 1",
    type: "Landmark Tower Display",
    rateUSD: 35,
    rateINR: 2905,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 17.0,
    height: 12.0,
    elevation: 68.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 62,
    offsetZ: 15,
    yaw: Math.PI,
  },
  {
    billboardNumber: 30,
    code: "bb_ts_landmark_upper_2",
    name: "Times Square Wedge Tower High-Screen 2",
    type: "Landmark Tower Display",
    rateUSD: 25,
    rateINR: 2075,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 17.0,
    height: 10.0,
    elevation: 82.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 62,
    offsetZ: 15,
    yaw: Math.PI,
  },

  // ── TIMES SQUARE EAST FRONTAGE (#31 – #41) ───────────────────────────
  {
    billboardNumber: 31,
    code: "bb_ts_east_corner_n",
    name: "Times Square East Corner Wrap (North)",
    type: "Folded Corner Screen",
    rateUSD: 85,
    rateINR: 7055,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 24.0,
    height: 12.0,
    elevation: 12.0,
    mount: "folded",
    orientation: "landscape",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: -34,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 32,
    code: "bb_ts_east_corner_s",
    name: "Times Square East Corner Wrap (South)",
    type: "Folded Corner Screen",
    rateUSD: 85,
    rateINR: 7055,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 24.0,
    height: 12.0,
    elevation: 12.0,
    mount: "folded",
    orientation: "landscape",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: 34,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 33,
    code: "bb_ts_east_portrait_1",
    name: "Times Square East Broadway Vertical Banner",
    type: "Vertical Building Banner",
    rateUSD: 65,
    rateINR: 5395,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 8.0,
    height: 18.0,
    elevation: 9.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: 12,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 34,
    code: "bb_ts_east_portrait_2",
    name: "Times Square East 7th Ave Vertical Banner",
    type: "Vertical Building Banner",
    rateUSD: 65,
    rateINR: 5395,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 8.0,
    height: 18.0,
    elevation: 9.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: -12,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 35,
    code: "bb_ts_east_upper",
    name: "Times Square East Upper Mega-Screen",
    type: "Building-Mounted Mega-Screen",
    rateUSD: 50,
    rateINR: 4150,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 20.0,
    height: 10.0,
    elevation: 28.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: 42,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 36,
    code: "bb_ts_east_facade_1",
    name: "Times Square East Mid-Rise Screen",
    type: "Building Facade Display",
    rateUSD: 50,
    rateINR: 4150,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 18.0,
    height: 9.0,
    elevation: 20.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: -42,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 37,
    code: "bb_ts_east_facade_2",
    name: "Times Square East Broadway Display",
    type: "Building Facade Display",
    rateUSD: 40,
    rateINR: 3320,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 16.0,
    height: 8.0,
    elevation: 12.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: 0,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 38,
    code: "bb_ts_east_ribbon_1",
    name: "Times Square East Avenue Ribbon",
    type: "Ribbon LED Screen",
    rateUSD: 20,
    rateINR: 1660,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 26.0,
    height: 4.0,
    elevation: 11.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: -20,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 39,
    code: "bb_ts_east_ribbon_2",
    name: "Times Square East Pedestrian Ribbon",
    type: "Ribbon LED Screen",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 26.0,
    height: 4.0,
    elevation: 24.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: 20,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 40,
    code: "bb_ts_east_wall_1",
    name: "Times Square East Lower Banner",
    type: "Vertical Wall Display",
    rateUSD: 35,
    rateINR: 2905,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 10.0,
    height: 14.0,
    elevation: 10.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: 50,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 41,
    code: "bb_ts_east_wall_2",
    name: "Times Square East High Banner",
    type: "Vertical Wall Display",
    rateUSD: 30,
    rateINR: 2490,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 10.0,
    height: 14.0,
    elevation: 26.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: 18.8,
    offsetZ: -50,
    yaw: -Math.PI / 2,
  },

  // ── TIMES SQUARE WEST FRONTAGE (#42 – #52) ───────────────────────────
  {
    billboardNumber: 42,
    code: "bb_ts_west_corner_n",
    name: "Times Square West Corner Wrap (North)",
    type: "Folded Corner Screen",
    rateUSD: 85,
    rateINR: 7055,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 24.0,
    height: 12.0,
    elevation: 12.0,
    mount: "folded",
    orientation: "landscape",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: -34,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 43,
    code: "bb_ts_west_corner_s",
    name: "Times Square West Corner Wrap (South)",
    type: "Folded Corner Screen",
    rateUSD: 85,
    rateINR: 7055,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 24.0,
    height: 12.0,
    elevation: 12.0,
    mount: "folded",
    orientation: "landscape",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: 34,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 44,
    code: "bb_ts_west_portrait_1",
    name: "Times Square West Broadway Vertical Banner",
    type: "Vertical Building Banner",
    rateUSD: 65,
    rateINR: 5395,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 8.0,
    height: 18.0,
    elevation: 9.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: -12,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 45,
    code: "bb_ts_west_portrait_2",
    name: "Times Square West 7th Ave Vertical Banner",
    type: "Vertical Building Banner",
    rateUSD: 65,
    rateINR: 5395,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 8.0,
    height: 18.0,
    elevation: 9.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: 12,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 46,
    code: "bb_ts_west_upper",
    name: "Times Square West Upper Mega-Screen",
    type: "Building-Mounted Mega-Screen",
    rateUSD: 50,
    rateINR: 4150,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 20.0,
    height: 10.0,
    elevation: 28.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: -42,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 47,
    code: "bb_ts_west_facade_1",
    name: "Times Square West Mid-Rise Screen",
    type: "Building Facade Display",
    rateUSD: 50,
    rateINR: 4150,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 18.0,
    height: 9.0,
    elevation: 20.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: 42,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 48,
    code: "bb_ts_west_facade_2",
    name: "Times Square West Broadway Display",
    type: "Building Facade Display",
    rateUSD: 40,
    rateINR: 3320,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 16.0,
    height: 8.0,
    elevation: 12.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: 0,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 49,
    code: "bb_ts_west_ribbon_1",
    name: "Times Square West Broadway Ribbon",
    type: "Ribbon LED Screen",
    rateUSD: 20,
    rateINR: 1660,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 26.0,
    height: 4.0,
    elevation: 11.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: 20,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 50,
    code: "bb_ts_west_ribbon_2",
    name: "Times Square West Pedestrian Ribbon",
    type: "Ribbon LED Screen",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 26.0,
    height: 4.0,
    elevation: 24.0,
    mount: "facade",
    orientation: "landscape",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: -20,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 51,
    code: "bb_ts_west_wall_1",
    name: "Times Square West Lower Banner",
    type: "Vertical Wall Display",
    rateUSD: 35,
    rateINR: 2905,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 10.0,
    height: 14.0,
    elevation: 10.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: -50,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 52,
    code: "bb_ts_west_wall_2",
    name: "Times Square West High Banner",
    type: "Vertical Wall Display",
    rateUSD: 30,
    rateINR: 2490,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 10.0,
    height: 14.0,
    elevation: 26.0,
    mount: "facade",
    orientation: "portrait",
    anchor: "times",
    offsetX: -18.8,
    offsetZ: 50,
    yaw: Math.PI / 2,
  },

  // ── TIMES SQUARE PLAZA PEDESTRIAN TOTEMS (#53 – #56) ─────────────────
  {
    billboardNumber: 53,
    code: "bb_ts_totem_nw",
    name: "Times Square Plaza Totem (North-West)",
    type: "Pedestrian Video Totem",
    rateUSD: 35,
    rateINR: 2905,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 6.0,
    height: 12.0,
    elevation: 1.6,
    mount: "pole",
    orientation: "portrait",
    anchor: "times",
    offsetX: -50,
    offsetZ: -28,
    yaw: Math.PI * 0.25,
  },
  {
    billboardNumber: 54,
    code: "bb_ts_totem_se",
    name: "Times Square Plaza Totem (South-East)",
    type: "Pedestrian Video Totem",
    rateUSD: 35,
    rateINR: 2905,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 6.0,
    height: 12.0,
    elevation: 1.6,
    mount: "pole",
    orientation: "portrait",
    anchor: "times",
    offsetX: 50,
    offsetZ: 28,
    yaw: -Math.PI * 0.75,
  },
  {
    billboardNumber: 55,
    code: "bb_ts_totem_ne",
    name: "Times Square Plaza Totem (North-East)",
    type: "Pedestrian Video Totem",
    rateUSD: 25,
    rateINR: 2075,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 5.0,
    height: 10.0,
    elevation: 1.6,
    mount: "pole",
    orientation: "portrait",
    anchor: "times",
    offsetX: 50,
    offsetZ: -28,
    yaw: -Math.PI * 0.25,
  },
  {
    billboardNumber: 56,
    code: "bb_ts_totem_sw",
    name: "Times Square Plaza Totem (South-West)",
    type: "Pedestrian Video Totem",
    rateUSD: 25,
    rateINR: 2075,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 5.0,
    height: 10.0,
    elevation: 1.6,
    mount: "pole",
    orientation: "portrait",
    anchor: "times",
    offsetX: -50,
    offsetZ: 28,
    yaw: Math.PI * 0.75,
  },
];

module.exports = { BILLBOARD_CATALOG };
