/**
 * Canonical constant billboard catalog - the single source of truth for what
 * the city has for sale.
 *
 *   #1 – #10   the original city-wide slots ($5 – $30 / month)
 *   #11 – #24  TIMES SQUARE ($35 – $90 / month)
 *
 * Times Square is the premium inventory and is priced accordingly: the square
 * sells advertising rather than real estate, so its buildings are never on the
 * market and the signage bolted to them is the only thing you can buy there.
 *
 * `mount` decides how a slot is physically carried, and must stay in step with
 * CITY_BILLBOARD_LOCATIONS in the frontend (brandShowcase.js):
 *   "facade"  bolted flat to a building wall - no pylons
 *   "folded"  two half panels wrapping a building corner in a shallow V
 *   "gantry"  straddling legs over a roadway
 *   "pole"    a free-standing pylon or plaza totem
 */
const BILLBOARD_CATALOG = [
  {
    billboardNumber: 1,
    code: "bb_commerce_ave",
    name: "Downtown Financial Avenue Mega-Screen",
    type: "Financial Hub Rooftop Billboard",
    rateUSD: 30,
    rateINR: 2490,
    billingCycle: "MONTHLY",
    plotDistrict: "Financial District",
    width: 15.0,
    height: 8.2,
    elevation: 12.0,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: 92,
    offsetZ: 32,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 2,
    code: "bb_cp_south",
    name: "Central Park South Mega-Gantry",
    type: "Overhead Highway Mega-Screen",
    rateUSD: 30,
    rateINR: 2490,
    billingCycle: "MONTHLY",
    plotDistrict: "Central Plaza",
    width: 14.0,
    height: 7.5,
    elevation: 8.0,
    mount: "gantry",
    orientation: "landscape",
    isGantry: true,
    offsetX: 0,
    offsetZ: 8,
    isPlazaZ1: true,
    yaw: 0,
  },
  {
    billboardNumber: 3,
    code: "bb_cp_north",
    name: "Central Park North Digital Plaza Screen",
    type: "Grand Plaza LED Billboard",
    rateUSD: 25,
    rateINR: 2075,
    billingCycle: "MONTHLY",
    plotDistrict: "Central Plaza",
    width: 12.0,
    height: 6.8,
    elevation: 7.0,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: 0,
    offsetZ: -8,
    isPlazaZ0: true,
    yaw: Math.PI,
  },
  {
    billboardNumber: 4,
    code: "bb_highway_east",
    name: "Commerce Highway Dual-Sided Gantry",
    type: "Highway Overhead LED Billboard",
    rateUSD: 20,
    rateINR: 1660,
    billingCycle: "MONTHLY",
    plotDistrict: "Commerce Way",
    width: 14.0,
    height: 7.2,
    elevation: 8.5,
    mount: "gantry",
    orientation: "landscape",
    isGantry: true,
    offsetX: 120,
    offsetZ: -45,
    yaw: 0,
  },
  {
    billboardNumber: 5,
    code: "bb_waterfront",
    name: "Waterfront Marina Scenic Billboard",
    type: "Coastal Marina Mega-Billboard",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Velora Harbor",
    width: 11.0,
    height: 6.2,
    elevation: 6.5,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: -120,
    offsetZ: 45,
    yaw: Math.PI,
  },
  {
    billboardNumber: 6,
    code: "bb_fountain_east",
    name: "Botanical Promenade East Video Totem",
    type: "Promenade Digital Pillar",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Botanical Gardens",
    width: 7.5,
    height: 9.5,
    elevation: 2.2,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: 28,
    offsetZ: 14,
    yaw: -Math.PI / 4,
  },
  {
    billboardNumber: 7,
    code: "bb_fountain_west",
    name: "Botanical Promenade West Video Totem",
    type: "Promenade Digital Pillar",
    rateUSD: 15,
    rateINR: 1245,
    billingCycle: "MONTHLY",
    plotDistrict: "Botanical Gardens",
    width: 7.5,
    height: 9.5,
    elevation: 2.2,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: -28,
    offsetZ: -14,
    yaw: Math.PI * 0.75,
  },
  {
    billboardNumber: 8,
    code: "bb_tech_hub",
    name: "Westside Tech District Video Totem",
    type: "Tech Hub Interactive Display",
    rateUSD: 10,
    rateINR: 830,
    billingCycle: "MONTHLY",
    plotDistrict: "Cyber District",
    width: 8.0,
    height: 8.5,
    elevation: 3.0,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: -88,
    offsetZ: -32,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 9,
    code: "bb_north_blvd",
    name: "North Coastal Boulevard LED Screen",
    type: "Boulevard Roadside Display",
    rateUSD: 10,
    rateINR: 830,
    billingCycle: "MONTHLY",
    plotDistrict: "Velora Harbor",
    width: 10.0,
    height: 6.0,
    elevation: 5.5,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: 42,
    offsetZ: -110,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 10,
    code: "bb_south_blvd",
    name: "South Parkview Boulevard Billboard",
    type: "Parkview Roadside Display",
    rateUSD: 5,
    rateINR: 415,
    billingCycle: "MONTHLY",
    plotDistrict: "Velora Outskirts",
    width: 10.0,
    height: 6.0,
    elevation: 5.5,
    mount: "pole",
    orientation: "landscape",
    isGantry: false,
    offsetX: -42,
    offsetZ: 110,
    yaw: -Math.PI / 2,
  },
  // ── TIMES SQUARE (#11 – #24) - the premium wall ─────────────────────
  {
    billboardNumber: 11,
    code: "bb_ts_north_marquee",
    name: "Times Square North Marquee",
    type: "Building-Mounted Mega-Screen",
    rateUSD: 90,
    rateINR: 7470,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 26.0,
    height: 13.0,
    elevation: 15.0,
    mount: "facade",
    orientation: "landscape",
    isGantry: false,
    anchor: "times",
    offsetX: -30,
    offsetZ: -16,
    yaw: 0,
  },
  {
    billboardNumber: 12,
    code: "bb_ts_north_tower",
    name: "Times Square North Tower Screen",
    type: "Building-Mounted Mega-Screen",
    rateUSD: 80,
    rateINR: 6640,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 22.0,
    height: 11.0,
    elevation: 31.0,
    mount: "facade",
    orientation: "landscape",
    isGantry: false,
    anchor: "times",
    offsetX: 34,
    offsetZ: -16,
    yaw: 0,
  },
  {
    billboardNumber: 13,
    code: "bb_ts_north_portrait",
    name: "Times Square North Vertical Banner",
    type: "Vertical Building Banner",
    rateUSD: 70,
    rateINR: 5810,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 9.0,
    height: 20.0,
    elevation: 9.0,
    mount: "facade",
    orientation: "portrait",
    isGantry: false,
    anchor: "times",
    offsetX: 2,
    offsetZ: -16,
    yaw: 0,
  },
  {
    billboardNumber: 14,
    code: "bb_ts_south_marquee",
    name: "Times Square South Marquee",
    type: "Building-Mounted Mega-Screen",
    rateUSD: 90,
    rateINR: 7470,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 26.0,
    height: 13.0,
    elevation: 14.0,
    mount: "facade",
    orientation: "landscape",
    isGantry: false,
    anchor: "times",
    offsetX: 30,
    offsetZ: 16,
    yaw: Math.PI,
  },
  {
    billboardNumber: 15,
    code: "bb_ts_south_portrait",
    name: "Times Square South Vertical Banner",
    type: "Vertical Building Banner",
    rateUSD: 70,
    rateINR: 5810,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 9.0,
    height: 20.0,
    elevation: 9.0,
    mount: "facade",
    orientation: "portrait",
    isGantry: false,
    anchor: "times",
    offsetX: -24,
    offsetZ: 16,
    yaw: Math.PI,
  },
  {
    billboardNumber: 16,
    code: "bb_ts_south_ribbon",
    name: "Times Square South Ribbon Board",
    type: "Wrap-Around Ribbon LED",
    rateUSD: 55,
    rateINR: 4565,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 24.0,
    height: 6.0,
    elevation: 26.0,
    mount: "facade",
    orientation: "landscape",
    isGantry: false,
    anchor: "times",
    offsetX: -46,
    offsetZ: 16,
    yaw: Math.PI,
  },
  {
    billboardNumber: 17,
    code: "bb_ts_east_corner",
    name: "Times Square East Corner Wrap",
    type: "Folded Corner Screen",
    rateUSD: 85,
    rateINR: 7055,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 24.0,
    height: 12.0,
    elevation: 12.0,
    mount: "folded",
    orientation: "landscape",
    isGantry: false,
    anchor: "times",
    offsetX: 20,
    offsetZ: -34,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 18,
    code: "bb_ts_east_portrait",
    name: "Times Square East Vertical Banner",
    type: "Vertical Building Banner",
    rateUSD: 65,
    rateINR: 5395,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 8.0,
    height: 18.0,
    elevation: 8.0,
    mount: "facade",
    orientation: "portrait",
    isGantry: false,
    anchor: "times",
    offsetX: 20,
    offsetZ: 12,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 19,
    code: "bb_ts_east_upper",
    name: "Times Square East Upper Screen",
    type: "Building-Mounted Mega-Screen",
    rateUSD: 75,
    rateINR: 6225,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 20.0,
    height: 10.0,
    elevation: 28.0,
    mount: "facade",
    orientation: "landscape",
    isGantry: false,
    anchor: "times",
    offsetX: 20,
    offsetZ: 42,
    yaw: -Math.PI / 2,
  },
  {
    billboardNumber: 20,
    code: "bb_ts_west_corner",
    name: "Times Square West Corner Wrap",
    type: "Folded Corner Screen",
    rateUSD: 85,
    rateINR: 7055,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 24.0,
    height: 12.0,
    elevation: 12.0,
    mount: "folded",
    orientation: "landscape",
    isGantry: false,
    anchor: "times",
    offsetX: -20,
    offsetZ: 34,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 21,
    code: "bb_ts_west_portrait",
    name: "Times Square West Vertical Banner",
    type: "Vertical Building Banner",
    rateUSD: 65,
    rateINR: 5395,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 8.0,
    height: 18.0,
    elevation: 8.0,
    mount: "facade",
    orientation: "portrait",
    isGantry: false,
    anchor: "times",
    offsetX: -20,
    offsetZ: -12,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 22,
    code: "bb_ts_west_upper",
    name: "Times Square West Upper Screen",
    type: "Building-Mounted Mega-Screen",
    rateUSD: 75,
    rateINR: 6225,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 20.0,
    height: 10.0,
    elevation: 28.0,
    mount: "facade",
    orientation: "landscape",
    isGantry: false,
    anchor: "times",
    offsetX: -20,
    offsetZ: -42,
    yaw: Math.PI / 2,
  },
  {
    billboardNumber: 23,
    code: "bb_ts_totem_nw",
    name: "Times Square Plaza Totem (North-West)",
    type: "Pedestrian Video Totem",
    rateUSD: 35,
    rateINR: 2905,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 6.0,
    height: 12.0,
    elevation: 1.6,
    mount: "pole",
    orientation: "portrait",
    isGantry: false,
    anchor: "times",
    offsetX: -52,
    offsetZ: -30,
    yaw: Math.PI * 0.25,
  },
  {
    billboardNumber: 24,
    code: "bb_ts_totem_se",
    name: "Times Square Plaza Totem (South-East)",
    type: "Pedestrian Video Totem",
    rateUSD: 35,
    rateINR: 2905,
    billingCycle: "MONTHLY",
    plotDistrict: "Times Square",
    width: 6.0,
    height: 12.0,
    elevation: 1.6,
    mount: "pole",
    orientation: "portrait",
    isGantry: false,
    anchor: "times",
    offsetX: 52,
    offsetZ: 30,
    yaw: -Math.PI * 0.75,
  },
];

module.exports = { BILLBOARD_CATALOG };

